python3 -m pip install auth0-python                
python3 -m pip install authlib
python3 -m pip install dash                     
python3 -m pip install dash-bootstrap-components
python3 -m pip install dash-core-components     
python3 -m pip install dash-html-components    
python3 -m pip install dash-renderer           
python3 -m pip install dash-table               
python3 -m pip install Flask                   
python3 -m pip install Flask-Compress          
python3 -m pip install glob2                 
python3 -m pip install Jinja2                   
python3 -m pip install numpy                    
python3 -m pip install pandas                  
python3 -m pip install plotly                   
python3 -m pip install pydantic
python3 -m pip install python-dotenv            
python3 -m pip install requests                 
python3 -m pip install urllib3                  
python3 -m pip install Werkzeug
pip3 install -r requirements.txt