on:
  push:
    branches: [ "main" , "master" ]

  workflow_dispatch:
  
jobs:
  docker:
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/docker.yml@logs-test
    secrets: inherit
    with:
      IMAGE_NAME: layinghens-dash
      CONTEXT: ./dash
      DOCKERFILE: ./dash/Dockerfile

  aws:
    needs: docker
    uses: GBADsInformatics/DevopsWorkflows/.github/workflows/aws.yml@logs-test
    secrets: inherit
    with:
      SERVICE_NAME: layinghens-dash-service
